version: 2
updates:
# Fetch and update latest `npm` or `yarn` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - moyomogi
  assignees:
    - moyomogi
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  # @see https://githubmemory.com/repo/ad-m/github-push-action/issues/96
  with:
    github_token: ${{ secrets.GH_PAT }}
